radius: 0.038
height: 0.25
obs_x: [-0.6, 0.6, 0.6]
obs_y: [-0.8, -0.8, 0.8]
x_length: 8.0
y_length: 8.0
wall_height: 0.25
thickness: 0.15
# robot_start_x: -0.6
# robot_start_y: 0.8
# robot_start_theta: 1.57
robot_start_x: 0.0
robot_start_y: 0.0
robot_start_theta: 0.0
basic_sensor_variance: 0.05
# max_laser_range: 3.5
max_laser_range: 0.5
collision_radius_robot: 0.11
wheel_cmd_mean: 0.0
wheel_cmd_variance: 0.01
fake_sensor_mean: 0.0
fake_sensor_variance: 0.01
laser_noise_mean: 0.0
laser_noise_variance: 0.01