radius: 0.038
height: 0.25
obs_x: [-0.6, 0.6, 0.6]
obs_y: [-0.8, -0.8, 0.8]
x_length: 5.0
y_length: 5.0
wall_height: 0.25
thickness: 0.15
robot_start_x: -0.6
robot_start_y: 0.8
robot_start_theta: 1.57
